### PR TITLE
Fix Jackett plugin

### PR DESCRIPTION
**Pull request by ngosang**

### CODE REVIEW

**Comment by bviktor** [comment]
Actually, this "fix" breaks the plugin. Can't download hits via Jackett anymore. Worked fine in 3.00.

**Comment by ngosang** [comment]
@bviktor What is your Jackett version? Do you use a reverse proxy for HTTPS? Nginx?

**Comment by bviktor** [comment]
0.10.880, but it's the same with 0.10.842. No reverse proxy, no HTTPS.

**Comment by ngosang** [comment]
@bviktor Update to 3.0.2 an tell me.

**Comment by bviktor** [comment]
Excellent, works perfectly now. Thanks a lot for the quick fix!

**Pull request merged**
