### PR TITLE
Add Prowlarr search engine

### PR DESCRIPTION
**Pull request by galeksandrp**
Tested on:

ASUS / `python 3.12.4` / `Windows 11 Home 22H2` / `qBittorrent 4.6.5` / `nova2.py CLI` 🆗 `GUI` 🆗 
XXL / `python 3.12.5` / `Arch Linux` / `qBittorrent 4.6.6` / `GUI` 🆗 `VueTorrent 2.12.0` 🆗

### CODE REVIEW

**Comment by xavier2k6** [comment]
@galeksandrp You will need to address CI failures.

**Comment by galeksandrp** [comment]
> @galeksandrp You will need to address CI failures.

done.

**Comment by Chocobo1** [comment]
@galeksandrp
Please don't reuse code across files. You should submit an independent file/plugin for your search engine.

**Comment by sunnyd24** [comment]
@galeksandrp I see this issue is closed. Did you succeed with committing this new Prowlarr plugin into qBittorrent master?

**Pull request closed without merging**
