### PR TITLE
oxtorrent search plugin

### PR DESCRIPTION
**Pull request by erdoukki**
Make oxtorrent search plugin work again (2021)

### CODE REVIEW

**Comment by thalieht** [comment]
If i'm not mistaken oxtorrent is French i.e. not English? In which case it probably won't be accepted as an official plugin.
And you're already giving patches to the existing unofficial plugin https://github.com/CravateRouge/qBittorrentSearchPlugins.

**Comment by erdoukki** [comment]
Do I must understand that english is the only official andnd only supported language ?

**Comment by thalieht** [comment]
>Do I must understand that english is the only official and only supported language ?

For an plugin to be official, yes.

**Comment by ngosang** [comment]
I'm not going to make this plugin official. Please, upload it to your repository and include it in the list of "unofficial plugins".
https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins

**Pull request closed without merging**
