### PR TITLE
Eztv

### PR DESCRIPTION
**Pull request by nindogo**
EZTV stopped working.

The site changed and this should resolve it.
Specifically  retrieve_url now has to be implemented in the script so as to track cookies and such.

### CODE REVIEW

**Comment by nindogo** [comment]
Hey @ngosang could you please look at this?

**Comment by xavier2k6** [comment]
https://eztvx.to/

**Comment by p060477** [comment]
how to add this as search plugin...??

**Comment by dmgolembiowski** [comment]
> how to add this as search plugin...??

In your configuration directory of qBittorrent, there can be a directory structure under it: `nova3/engines` which gets populated when you update your search plugins (after specifying a path). Just put the Python file under the `engines` directory and restart qBittorrent.

**Comment by xavier2k6** [comment]
@nindogo Why is the random user agent required?

**Comment by xavier2k6** [comment]
Superseded by #291.

**Pull request closed without merging**
