### PR TITLE
Download all plugins for public sites by executing this Python script.

### PR DESCRIPTION
**Pull request by Emporea**
I know this may not be the appropriate method of contribution to this repository, but I believe it to be valuable. Perhaps it may benefit others.

### CODE REVIEW

**Comment by p060477** [comment]
hi, how to use it...??
could you pls guide step by step...??
i'm on win 10 home 64 desktop

**Comment by p060477** [comment]
hi, first thxs so much

"You need a python environment installed. There are many tutorials out there. https://www.python.org/downloads/

Then you need to install [beautifulsoup4](https://pypi.org/project/beautifulsoup4/) using pip install beautifulsoup4."..:
- done ! -

so now i'm here:
"Then you should be able to execute the python file using python PublicPluginDownloader.py .
This will download all .py files into a subfolder."...:
pls guide me as i was a blind child.....
thxs so much in avd
cheers

**Comment by p060477** [comment]
done!!...:

Downloaded plugins\one337x.py
Downloaded plugins\academictorrents.py
Downloaded plugins\acgrip.py
Downloaded plugins\ali213.py
Downloaded plugins\anidex.py
Downloaded plugins\audiobookbay.py
Downloaded plugins\bt4g.py
Downloaded plugins\bt4gprx.py
Downloaded plugins\btetree.py
Downloaded plugins\btmulu.py
Downloaded plugins\cinecalidad.py
Downloaded plugins\cpasbien.py
Downloaded plugins\darklibria.py
Downloaded plugins\dmhyorg.py
Downloaded plugins\elitetorrent.py
Downloaded plugins\extratorrent.py
Downloaded plugins\glotorrents.py
Downloaded plugins\ilcorsaronero.py
Downloaded plugins\kickasstorrents.py
Downloaded plugins\linuxtracker.py
Downloaded plugins\magnetdl.py
Downloaded plugins\magnetdl_1.py
Downloaded plugins\maxitorrent.py
Downloaded plugins\mejor.py
Downloaded plugins\mikanani.py
Downloaded plugins\nitro.py
Downloaded plugins\pantsu.py
Downloaded plugins\nyaapantsu.py
Downloaded plugins\nyaasi.py
Downloaded plugins\oxtorrent.py
Downloaded plugins\pctfenix.py
Downloaded plugins\pctmix.py
Downloaded plugins\pctreload.py
Downloaded plugins\pirateiro.py
Downloaded plugins\rockbox.py
Downloaded plugins\rutor.py
Downloaded plugins\smallgames.py
Downloaded plugins\snowfl.py
Downloaded plugins\solidtorrents.py
Downloaded plugins\subtorrents.py
Downloaded plugins\sukebeisi.py
Downloaded plugins\nyaa.py
Downloaded plugins\sukebei.py
Downloaded plugins\thepiratebay.py
Downloaded plugins\thepiratebay_1.py
Downloaded plugins\tntvillagedump.py
Downloaded plugins\tokyotoshokan.py
Downloaded plugins\torrent9.py
Downloaded plugins\torrentdownload.py
Downloaded plugins\torrentdownload_1.py
Downloaded plugins\torrentfunk.py
Downloaded plugins\torrentgalaxy.py
Downloaded plugins\torrentproject.py
Downloaded plugins\uniondht.py
Downloaded plugins\yourbittorrent.py
Downloaded plugins\yts.py
Downloaded plugins\yts_am.py


and now...??...how to use them in qbittorrent...??

thxs so much again

cheers!

**Comment by p060477** [comment]
> They have this `_1` because a file with the same name already existed. You need to decide on your own which one of them to keep or rename them completly and remove the `_1`.
> 

hi also renaming them it always reply the same error:
"extension not supported"...:(

**Comment by p060477** [comment]
> How did you name them

for ex:
magnetdl_1.py
remaned in:
magnet.py

...is there a different usefull way...??..if yes pls show me 
thxs again for yr kind attn
cheers

**Comment by p060477** [comment]
> Did you restart your qbittorrent?

just exit qbittorrent and restart...
same error:
"impossible to install: ext. not supported"... :(

**Comment by p060477** [comment]
> I am afraid I cannot help you without more useful information. Are you sure that the file extension is still '.py'?

of course...
here it is the screenshoot of the plugins subfolder:

Immagine

i renamed the :
magnetdl_1.py
torrentdownload_1.py
thepiratebay_1.py

in:
magnet.py
torrentdownld.py
thepirateby.py

and all these renamed files get the same error:
"impossible to install: ext. not supported"... :(

**Comment by p060477** [comment]
> You still have files with the suffix _1 in that directory, you need to delete or rename them all. 

...i'm afraid that was not the matter...here is the new screenshoot....i've deleted the " _1 " as for yr instructions..:
Immagine

but the issue is still there...:

magnet.py
torrentdownld.py
thepirateby.py

all these 3 renamed files get the same error:
"impossible to install: ext. not supported"... :(

**Comment by p060477** [comment]
the strange thing is that only thse 3 have the issue...and surely 2 of them are different from the same-named...
i mean magnetdl.py is 2kb and the same-named "_1" is of 4kb so they are completely different.....
samer thing for thepiratebay...2kb against 4kb...totally different...so which choose...??.....
cause if i delete the .
magnetdl.py, which has no issue
and i re-name exactly the magnetdl_1.py as magnetdl.py i get no error.....
so which one of the 2 should i have to choose...
is a real mess......:(

**Comment by p060477** [comment]
> It is your choice which one to keep. I think you can only have 1 plugin per site. In the files themselves you will often see a VERSION at the top. Just keep the file with the higher version.
> 
> Will update the script soon so it doesnt break. Thanks for the feedback and I hope I was able to help.

GOAL!!...:
the genial ide was to see the higher vers.!!
and in 2 of the 3 cases the "_1" was higher...
so i delete the same-named and renamed that deleting the "_1" part...
and it works!!
now i've all fine and working!!
thxs so much indeed to you
for yr attention
but also for yr very gentle and so kind patience
have a nice week
and lots of compliments for yr script!
cheers
:)

**Comment by Pina1924** [comment]
hi, last prayer : 
when you update this yr precious script pls send us an alert in order to let us know
 and let us able to update it in time!!
thxs so much again
cheers

**Comment by Pina1924** [comment]
@Emporea: why you close and delete the head repository...??... :(

Inviato con l'email sicura [Proton Mail](https://proton.me/).

------- Original Message -------
Il giovedì 26 ottobre 2023 03:03, Emporea ***@***.***> ha scritto:

**Pull request closed without merging**
