### PR TITLE
Repaired demonoid search engine

### PR DESCRIPTION
**Pull request by hannsen**
* fixed download link match 
* fixed torrent list detection regex 
* enabled strict search
* small formatting changes

### CODE REVIEW

**Comment by Chocobo1** [comment]
@hannsen 
Do you wish to adopt this plugin?
I mean this plugin will become unofficial and you will maintain it.

If so, please add an entry in https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins
and let me know.

**Comment by Pireo** [comment]
@ngosang

**Comment by hannsen** [comment]
@Chocobo1 I could, but whats the reason for not merging it?

I also had in mind to use threading to run multiple search pages in parallel for faster execution time.
Would you merge such changes or should I do them as unofficial?

**Comment by Chocobo1** [comment]
>I could, but whats the reason for not merging it?

Since the other maintainer is absent and I have low interest, it is best for the plugin to turn unofficial to live on.

**Comment by hannsen** [comment]
added as unofficial
https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins

**Comment by Chocobo1** [comment]
>added as unofficial

Thank you

**Pull request closed without merging**
