### PR TITLE
Update SolidTorrents search engine

### PR DESCRIPTION
**Pull request by WolfganP**
Site moved to https://solidtorrents.to/, new search tested with nova

### CODE REVIEW

**Comment by xavier2k6** [comment]
@WolfganP `versions.txt` needs to be updated & in #270 too.

**Comment by WolfganP** [comment]
> @WolfganP `versions.txt` needs to be updated & in #270 too.

Done in both of them. Thx for the tip!

**Comment by xavier2k6** [comment]
>, mod by WolfganP

Not sure if that's allowed....anyway, will ping @ngosang & @Chocobo1 to review open PR's when they're ready.

**Comment by xavier2k6** [comment]
Closes #279.

**Comment by xavier2k6** [comment]
Tested - confirmed fixed.

**Comment by xavier2k6** [comment]
>, mod by WolfganP

@WolfganP remove above comment from both your PR's & rebase/make 1 commit & will approve.

**Comment by xavier2k6** [comment]
@WolfganP this PR has been superseded by #287 & have credited you with being a co-author.

**Pull request closed without merging**
