### PR TITLE
Adding torrents-csv to search engines.

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

**Comment by dessalines** [comment]
Additional questions

1. Torrents.csv has no concept of categories, just all... did I do that right? It appears to work fine locally.
2. Torrents.csv can also search for files, and this is simple to add into this plugin. How would I do this, maybe create a 'files' category to flip between searching for torrents, vs searching for files?

**Comment by ngosang** [comment]
Added in #116.
Although it is not very popular, I have added it because it has good content and the UI /API is clear. If users start reporting something is wrong with the site (fakes, malware, advertising...) I will remove it forever.
Regarding the categories it is not necessary to support them.
We do not support file search right now. I leave the search by title.
Thank you.

**Comment by ngosang** [comment]
@dessalines Some advices:
* From now the site has official support. You don't need to keep outdated versions => https://gitlab.com/dessalines/torrents.csv/tree/master/qBittorrent Just open PRs with your changes.
* Build the magnet link in the server so we don't have to do it in your web UI, qBittorrent, Jackett... I recommend you my lists => https://github.com/ngosang/trackerslist
* Improve the search. With `bieber justin` I'm not getting results.
* Provide a combined search with title and files (in 1 request). I will use the title only but can be interesting for someone.

**Comment by dessalines** [comment]
Thanks! I do use your tracker list also in the web front end, but I can build it on the back end as well.

> Improve the search. With bieber justin I'm not getting results.

That's fair, for right now its ordering the text in a sql query: `select * from torrent where name like '%bunch% %of% %search% %terms%'`. I'll have to think of ways to query (without using postgres' full text search).

> Provide a combined search with title and files (in 1 request). I will use the title only but can be interesting for someone.

The files search prepends the torrent name, so it should work for finding both, if I understand you correctly.

Also I just wanted to note this issue for a BEP extension I created that's been approved, and has libtorrent support, but only 1 client has implemented it (libretorrent for android) : https://github.com/qbittorrent/qBittorrent/issues/7341

[BEP53](http://www.bittorrent.org/beps/bep_0053.html)

Lets say you just want to download **only one song** from an album, or an artists discography. This adds a `select only` param to the magnet link, and after the metadata is downloaded, the client will only select that specific file for download. This works great for library torrents, and I'd love to see it in qbittorrent.

**Pull request closed without merging**
