### PR TITLE
Remove 'others' categories in zoogle plugin

### PR DESCRIPTION
**Pull request by Chocobo1**
This fixes the blank category entry appearing in qBittorrent:
https://github.com/qbittorrent/qBittorrent/issues/7109

### CODE REVIEW

**Comment by ngosang** [comment]
Make same changes in nova2.
Increase plugin version in .py and version.txt files

**Comment by ngosang** [comment]
@Chocobo1 Could you do that? https://github.com/qbittorrent/qBittorrent/pull/6883#issuecomment-314207956

**Comment by Chocobo1** [comment]
>Make same changes in nova2.
Increase plugin version in .py and version.txt files

Thanks, done.

>@Chocobo1 Could you do that? qbittorrent/qBittorrent#6883 (comment)

You mean "easy installer"? Can you be more specific? or an example.

**Comment by ngosang** [comment]
> You mean "easy installer"? Can you be more specific? or an example.

If you download qBittorrent for the fist time, search engine is disabled. Ok, you enable it but you don't have any search engine, you have to install all of them manually. This is too much work for the average user.
1) In the plugins list should appear all installed plugins and all available plugins in this repository.
2) Rename column "Enabled" to "Status". All statuses are ""Enabled", "Disabled", "Not installed"
3) If Status = "Not installed" you can select "Install" and the plugin is downloaded and installed from this repository.
4) If you uninstall one plugin (and it's available in this repository) you will see again "Not installed" and you can install if again re-downloading.

**Pull request merged**
