### PR TITLE
Add eztv search plugin

### PR DESCRIPTION
**Pull request by ngosang**

### CODE REVIEW

**Comment by Chocobo1** [comment]
BTW, I plan to add pep8 checker to CI, what do you think? Will it be too strict?

**Comment by ngosang** [comment]
It's a bit strict for me but it's ok, go on.
I think you should add the python checks also in https://github.com/qbittorrent/qBittorrent/tree/master/src/searchengine

**Comment by Pireo** [comment]
@ngosang I respectfully disagree with this, for two reasons:
1) the .ag domain is not legit
2) the site only supports one category, even an illegal one

if you want to add another site my recommendation is Limetorrents, and if you want to include a further one with a single category then linuxtracker comes to my mind, since it has 100% legal content and a lot of linux users are on qBt.

**Comment by ngosang** [comment]
I know they are not the original eztv group, but the torrents are good and is in the top10 torrent sites.
https://torrentfreak.com/top-10-most-popular-torrent-sites-of-2018-180107/

I can make Limetorrents official but the unofficial plugin needs a fix.

**Comment by Pireo** [comment]
yts is even higher, doesnt mean we should include it (and it would be impossibile since it requires to choose resolutions). Limetorrents is 7th, so even from a popularity perspective deserves a chance imho. Maybe the site is obscured in your country? If you change yout dns with google ones you should reach it and the plugin will eventually work.

**Comment by ngosang** [comment]
@Pireo Limetorrents =>  #51

**Comment by Pireo** [comment]
Thanks, but if you are sure you want to include this plugin, I'll delete it in the unofficial page.

**Comment by ngosang** [comment]
@Pireo I did

**Comment by slrslr** [comment]
I have found this eztv.re plugin v. 1.14 yet it returns 50 irrelevant results each time i search. So i should remove it i guess..

**Pull request merged**
